[auth]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes_enabled = false
enable_confirmations = false

[functions.calculate-shipping]
verify_jwt = false

[functions.paguelo-facil-create-payment]
verify_jwt = false

[functions.paguelo-facil-get-status]
verify_jwt = false

[functions.paguelo-facil-validate-payment]
verify_jwt = false

[functions.paguelo-facil-webhook]
verify_jwt = false

[functions.servientrega-cotizar]
verify_jwt = true

[functions.servientrega-generar-guia]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-order-confirmation-email]
verify_jwt = false

[functions.loyverse-update-inventory]
verify_jwt = false
