/**
 * Datos completos de ubicaciones de Servientrega
 * Generado desde el CSV oficial de Servientrega
 */

export interface ServientregaLocation {
  corregimiento: string;
  distrito: string;
  provincia: string;
}

export const SERVIENTREGA_LOCATIONS: ServientregaLocation[] = [
  { corregimiento: "ALMIRANTE", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "BAJO CEDRO", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "BASTIMENTOS", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "BOCAS DEL TORO", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "CAUCHERO", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "CHANGUINOLA", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "CHIRIQUI", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "CHIRIQUI GRANDE -BOCAS", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "COCHIGRO", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "EL EMPALME", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "EL VALLE DE AGUA ARRIBA", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "GUABITO", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "ISLA  BOCAS", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "LA GLORIA", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "LAS DELICIAS", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "LAS TABLAS", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "MIRAMAR", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "NANCE DE RISCO", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "PUNTA LAUREL", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "PUNTA PENA", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "PUNTA ROBALO", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "RAMBALA", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "TERIBE", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "TIERRA OSCURA", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "VALLE DEL RISCO", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "24 DE DICIEMBRE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "AMADOR", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "AMELIA DENIS DE ICAZA", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "ANCON", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "ARNULFO ARIAS", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "AROSEMENA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "ARRAIJAN", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "BARRIO BALBOA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "BARRIO COLON", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "BEJUCO", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "BELISARIO FRIAS", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "BELISARIO PORRAS", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "BELLA VISTA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "BETHANIA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "BRUJAS", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "BUENOS AIRES", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "BURUNGA", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "CABUYA", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "CAIMITO", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CAMPANA", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CANITA", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "CAPIRA", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CERMENO", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CERRO AZUL", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "CERRO SILVESTRE", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "CHAME", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "CHEPILLO", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "CHEPO", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "CHICA", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "CHILIBRE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "CHIMAN", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "CIRI DE LOS SOTOS", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CIRI GRANDE", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CIUDAD DE PANAMA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "CIUDAD DE PANAMA OESTE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "CIUDAD PANAMA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "COMARCA KUNA DE MADUGANDI", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "CORONADO", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "CURUNDU", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "EL ARADO", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "EL CACAO", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "EL CHORRILLO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "EL COCO", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "EL ESPINO", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "EL HIGO", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "EL LIBANO", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "EL LLANO", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "FEUILLET", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "GONZALO VASQUEZ", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "GUADALUPE", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "GUAYABITO", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "HERRERA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "HERRERA DE CHORRERA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "HURTADO", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "ITURRALDE", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "JOSE DOMINGO ESPINAR", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "JUAN DEMOSTENES AROSEMENA", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "JUAN DIAZ", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "LA CHORRERA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "LA ENSENADA", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "LA ERMITA", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "LA ESMERALDA", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "LA EXPOSICION O CALIDONIA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "LA GUINEA", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "LA LAGUNA", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "LA REPRESA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "LA TRINIDAD", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "LAS CUMBRES", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "LAS LAJAS CHAME", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "LAS MANANITAS", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "LAS MARGARITAS", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "LAS OLLAS ARRIBA", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "LAS UVAS", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "LIDICE", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "LOS DIAZ", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "LOS LLANITOS", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "MATEO ITURRALDE", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "MENDOZA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "NUEVA GORGONA", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "NUEVO EMPERADOR", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "OBALDIA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "OMAR TORRIJOS", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "OTOQUE OCCIDENTE", distrito: "TABOGA", provincia: "PANAMA" },
  { corregimiento: "OTOQUE ORIENTE", distrito: "TABOGA", provincia: "PANAMA" },
  { corregimiento: "PACORA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "PARQUE LEFEVRE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "PASIGA", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "PEDREGAL", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "PEDRO GONZALEZ", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "PLAYA LEONA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "PUEBLO NUEVO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "PUERTO CAIMITO", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "PUNTA CHAME", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "RIO ABAJO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "RUFINA ALFARO", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "SABOGA", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "SAJALICES", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "SAN CARLOS", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "SAN FELIPE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SAN FRANCISCO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SAN JOSE", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "SAN MARTIN", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SAN MIGUEL", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "SAN MIGUELITO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SANTA ANA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SANTA CLARA", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "SANTA CRUZ DE CHININA", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "SANTA RITA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "SANTA ROSA", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "SORA", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "TABOGA", distrito: "TABOGA", provincia: "PANAMA" },
  { corregimiento: "TOCUMEN", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "TORTI", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "UNION SANTENA", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "VERACRUZ", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "VICTORIANO LORENZO", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "VILLA CARMEN", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "VILLA ROSARIO", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "VISTA ALEGRE", distrito: "ARRAIJAN", provincia: "PANAMA" },
];
