/**
 * Datos completos de ubicaciones de Servientrega
 * Generado desde el CSV oficial de Servientrega
 */

export interface ServientregaLocation {
  corregimiento: string;
  distrito: string;
  provincia: string;
}

export const SERVIENTREGA_LOCATIONS: ServientregaLocation[] = [
  { corregimiento: "ALMIRANTE", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "BAJO CEDRO", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "BASTIMENTOS", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "BOCAS DEL TORO", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "CAUCHERO", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "CHANGUINOLA", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "CHIRIQUI", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "CHIRIQUI GRANDE -BOCAS", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "COCHIGRO", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "EL EMPALME", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "EL VALLE DE AGUA ARRIBA", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "GUABITO", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "ISLA  BOCAS", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "LA GLORIA", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "LAS DELICIAS", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "LAS TABLAS", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "MIRAMAR", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "NANCE DE RISCO", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "PUNTA LAUREL", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "PUNTA PENA", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "PUNTA ROBALO", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "RAMBALA", distrito: "CHIRIQUI GRANDE", provincia: "BOCAS DEL TORO" },
  { corregimiento: "TERIBE", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "TIERRA OSCURA", distrito: "BOCAS DEL TORO", provincia: "BOCAS DEL TORO" },
  { corregimiento: "VALLE DEL RISCO", distrito: "CHANGUINOLA", provincia: "BOCAS DEL TORO" },
  { corregimiento: "ALANJE", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "ALTO BOQUETE", distrito: "BOQUETE", provincia: "CHIRIQUI" },
  { corregimiento: "ASERRIO DE GARICHE", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "BACO", distrito: "BARU", provincia: "CHIRIQUI" },
  { corregimiento: "BAGALA", distrito: "BOQUERON", provincia: "CHIRIQUI" },
  { corregimiento: "BAJO BOQUETE", distrito: "BOQUETE", provincia: "CHIRIQUI" },
  { corregimiento: "BELLA VISTA", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "BIJAGUAL", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "BOCA CHICA", distrito: "SAN LORENZO", provincia: "CHIRIQUI" },
  { corregimiento: "BOCA DEL MONTE", distrito: "SAN LORENZO", provincia: "CHIRIQUI" },
  { corregimiento: "BOQUERON", distrito: "BOQUERON", provincia: "CHIRIQUI" },
  { corregimiento: "BOQUETE", distrito: "", provincia: "CHIRIQUI" },
  { corregimiento: "BRENON", distrito: "RENACIMIENTO", provincia: "CHIRIQUI" },
  { corregimiento: "BUGABA", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "CALDERA", distrito: "BOQUETE", provincia: "CHIRIQUI" },
  { corregimiento: "CANAS GORDAS", distrito: "RENACIMIENTO", provincia: "CHIRIQUI" },
  { corregimiento: "CANTA GALLO", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "CERRO PUNTA", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "CERRO VIEJO", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "CHIRIQUI", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "COCHEA", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "CORDILLERA", distrito: "BOQUERON", provincia: "CHIRIQUI" },
  { corregimiento: "CORONADO", distrito: "", provincia: "CHIRIQUI" },
  { corregimiento: "DAVID", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "DIVALA", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "DOLEGA", distrito: "DOLEGA", provincia: "CHIRIQUI" },
  { corregimiento: "DOMINICAL", distrito: "RENACIMIENTO", provincia: "CHIRIQUI" },
  { corregimiento: "DOS RIOS", distrito: "DOLEGA", provincia: "CHIRIQUI" },
  { corregimiento: "EL BONGO", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "EL CRISTO", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "EL NANCITO", distrito: "REMEDIOS", provincia: "CHIRIQUI" },
  { corregimiento: "EL PORVENIR", distrito: "REMEDIOS", provincia: "CHIRIQUI" },
  { corregimiento: "EL PUERTO", distrito: "REMEDIOS", provincia: "CHIRIQUI" },
  { corregimiento: "EL TEJAR", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "GOMEZ", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "GUABAL", distrito: "BOQUERON", provincia: "CHIRIQUI" },
  { corregimiento: "GUACA", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "GUALACA", distrito: "GUALACA", provincia: "CHIRIQUI" },
  { corregimiento: "GUARUMAL", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "GUAYABAL", distrito: "BOQUERON", provincia: "CHIRIQUI" },
  { corregimiento: "HORCONCITOS", distrito: "SAN LORENZO", provincia: "CHIRIQUI" },
  { corregimiento: "HORNITO", distrito: "GUALACA", provincia: "CHIRIQUI" },
  { corregimiento: "JARAMILLO", distrito: "BOQUETE", provincia: "CHIRIQUI" },
  { corregimiento: "JUAY", distrito: "SAN FELIX", provincia: "CHIRIQUI" },
  { corregimiento: "JUSTO FIDEL PALACIOS", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "LA CONCEPCION", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "LA ESTRELLA", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "LAJAS ADENTRO", distrito: "SAN FELIX", provincia: "CHIRIQUI" },
  { corregimiento: "LAJAS DE TOLE", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "LAS LAJAS", distrito: "", provincia: "CHIRIQUI" },
  { corregimiento: "LAS LAJAS SAN FELIX", distrito: "SAN FELIX", provincia: "CHIRIQUI" },
  { corregimiento: "LAS LOMAS", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "LIMONES", distrito: "BARU", provincia: "CHIRIQUI" },
  { corregimiento: "LOS ALGARROBOS", distrito: "DOLEGA", provincia: "CHIRIQUI" },
  { corregimiento: "LOS ANASTACIOS", distrito: "DOLEGA", provincia: "CHIRIQUI" },
  { corregimiento: "LOS ANGELES", distrito: "GUALACA", provincia: "CHIRIQUI" },
  { corregimiento: "LOS NARANJOS", distrito: "BOQUETE", provincia: "CHIRIQUI" },
  { corregimiento: "MONTE LIRIO", distrito: "RENACIMIENTO", provincia: "CHIRIQUI" },
  { corregimiento: "NUEVO MEXICO", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "PAJA DE SOMBRERO", distrito: "GUALACA", provincia: "CHIRIQUI" },
  { corregimiento: "PALMIRA", distrito: "BOQUETE", provincia: "CHIRIQUI" },
  { corregimiento: "PALO GRANDE", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "PARAISO", distrito: "BOQUERON", provincia: "CHIRIQUI" },
  { corregimiento: "PASO CANOAS FRONTERA", distrito: "", provincia: "CHIRIQUI" },
  { corregimiento: "PEDREGAL", distrito: "BOQUERON", provincia: "CHIRIQUI" },
  { corregimiento: "PLAZA CAISAN", distrito: "RENACIMIENTO", provincia: "CHIRIQUI" },
  { corregimiento: "POTRERILLOS", distrito: "DOLEGA", provincia: "CHIRIQUI" },
  { corregimiento: "POTRERILLOS ABAJO", distrito: "DOLEGA", provincia: "CHIRIQUI" },
  { corregimiento: "POTRERO DE CANA", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "PROGRESO", distrito: "BARU", provincia: "CHIRIQUI" },
  { corregimiento: "PUERTO ARMUELLES", distrito: "", provincia: "CHIRIQUI" },
  { corregimiento: "PUERTO ARMUELLESABECER", distrito: "BARU", provincia: "CHIRIQUI" },
  { corregimiento: "QUEBRADA DE PIEDRA", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "QUEREVALO", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "REMEDIOS", distrito: "REMEDIOS", provincia: "CHIRIQUI" },
  { corregimiento: "RINCON", distrito: "GUALACA", provincia: "CHIRIQUI" },
  { corregimiento: "RIO SERENO", distrito: "RENACIMIENTO", provincia: "CHIRIQUI" },
  { corregimiento: "RODOLFO AGUILAR DELGADO", distrito: "BARU", provincia: "CHIRIQUI" },
  { corregimiento: "ROVIRA", distrito: "DOLEGA", provincia: "CHIRIQUI" },
  { corregimiento: "SAN ANDRES", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "SAN CARLOS", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "SAN FELIX", distrito: "SAN FELIX", provincia: "CHIRIQUI" },
  { corregimiento: "SAN JUAN", distrito: "SAN LORENZO", provincia: "CHIRIQUI" },
  { corregimiento: "SAN LORENZO", distrito: "SAN LORENZO", provincia: "CHIRIQUI" },
  { corregimiento: "SAN PABLO NUEVO", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "SAN PABLO VIEJO", distrito: "DAVID", provincia: "CHIRIQUI" },
  { corregimiento: "SANTA CLARA", distrito: "RENACIMIENTO", provincia: "CHIRIQUI" },
  { corregimiento: "SANTA CRUZ", distrito: "RENACIMIENTO", provincia: "CHIRIQUI" },
  { corregimiento: "SANTA LUCIA", distrito: "REMEDIOS", provincia: "CHIRIQUI" },
  { corregimiento: "SANTA MARTA", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "SANTA ROSA", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "SANTO DOMINGO", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "SANTO TOMAS", distrito: "ALANJE", provincia: "CHIRIQUI" },
  { corregimiento: "SORTOVA", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "STRASBUSGO", distrito: "", provincia: "CHIRIQUI" },
  { corregimiento: "TIJERAS", distrito: "BOQUERON", provincia: "CHIRIQUI" },
  { corregimiento: "TINAJAS", distrito: "DOLEGA", provincia: "CHIRIQUI" },
  { corregimiento: "TOLE", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "VELADERO", distrito: "TOLE", provincia: "CHIRIQUI" },
  { corregimiento: "VOLCAN", distrito: "BUGABA", provincia: "CHIRIQUI" },
  { corregimiento: "AGUADULCE", distrito: "AGUADULCE", provincia: "COCLE" },
  { corregimiento: "ANTON", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "BARRIOS UNIDOS", distrito: "AGUADULCE", provincia: "COCLE" },
  { corregimiento: "CABALLERO", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "CABUYA", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "CANAVERAL", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "CAPELLANIA", distrito: "NATA DE LOS CABALLEROS", provincia: "COCLE" },
  { corregimiento: "CHIGUIRI ARRIBA", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "COCLE", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "EL CANO", distrito: "NATA DE LOS CABALLEROS", provincia: "COCLE" },
  { corregimiento: "EL CHIRU", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "EL COCO", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "EL COPE", distrito: "OLA", provincia: "COCLE" },
  { corregimiento: "EL CRISTO", distrito: "AGUADULCE", provincia: "COCLE" },
  { corregimiento: "EL HARINO", distrito: "LA PINTADA", provincia: "COCLE" },
  { corregimiento: "EL PALMAR", distrito: "OLA", provincia: "COCLE" },
  { corregimiento: "EL PICACHO", distrito: "OLA", provincia: "COCLE" },
  { corregimiento: "EL POTRERO", distrito: "LA PINTADA", provincia: "COCLE" },
  { corregimiento: "EL RETIRO", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "EL ROBLE", distrito: "AGUADULCE", provincia: "COCLE" },
  { corregimiento: "EL VALLE", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "GUZMAN", distrito: "NATA DE LOS CABALLEROS", provincia: "COCLE" },
  { corregimiento: "JUAN DIAZ", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "LA PAVA", distrito: "OLA", provincia: "COCLE" },
  { corregimiento: "LA PINTADA", distrito: "LA PINTADA", provincia: "COCLE" },
  { corregimiento: "LAS HUACAS", distrito: "NATA DE LOS CABALLEROS", provincia: "COCLE" },
  { corregimiento: "LAS LOMAS", distrito: "LA PINTADA", provincia: "COCLE" },
  { corregimiento: "LLANO GRANDE", distrito: "LA PINTADA", provincia: "COCLE" },
  { corregimiento: "NATA", distrito: "NATA DE LOS CABALLEROS", provincia: "COCLE" },
  { corregimiento: "OLA", distrito: "OLA", provincia: "COCLE" },
  { corregimiento: "PAJONAL", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "PENONOME", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "PIEDRAS GORDAS", distrito: "LA PINTADA", provincia: "COCLE" },
  { corregimiento: "POCRI", distrito: "AGUADULCE", provincia: "COCLE" },
  { corregimiento: "RIO GRANDE", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "RIO HATO", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "RIO INDIO", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "SAN JUAN DE DIOS", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "SANTA RITA", distrito: "ANTON", provincia: "COCLE" },
  { corregimiento: "TOABRE", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "TOZA", distrito: "NATA DE LOS CABALLEROS", provincia: "COCLE" },
  { corregimiento: "TULU", distrito: "PENONOME", provincia: "COCLE" },
  { corregimiento: "ACHIOTE", distrito: "CHAGRES", provincia: "COLON" },
  { corregimiento: "BARRIO NORTE", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "BARRIO SUR", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "BUENA VISTA", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "CACIQUE", distrito: "PORTOBELO", provincia: "COLON" },
  { corregimiento: "CATIVA", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "CIRICITO", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "COCLE DEL NORTE", distrito: "DONOSO", provincia: "COLON" },
  { corregimiento: "COLON", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "CRISTOBAL", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "CUANGO", distrito: "SANTA ISABEL", provincia: "COLON" },
  { corregimiento: "EL GUABO", distrito: "CHAGRES", provincia: "COLON" },
  { corregimiento: "EL GUASIMO", distrito: "DONOSO", provincia: "COLON" },
  { corregimiento: "ESCOBAL", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "GARROTE", distrito: "PORTOBELO", provincia: "COLON" },
  { corregimiento: "GOBEA", distrito: "DONOSO", provincia: "COLON" },
  { corregimiento: "ISLA GRANDE", distrito: "PORTOBELO", provincia: "COLON" },
  { corregimiento: "LA ENCANTADA", distrito: "CHAGRES", provincia: "COLON" },
  { corregimiento: "LIMON", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "MARIA CHIQUITA", distrito: "PORTOBELO", provincia: "COLON" },
  { corregimiento: "MIGUEL DE LA BORDA", distrito: "DONOSO", provincia: "COLON" },
  { corregimiento: "MIRAMAR", distrito: "SANTA ISABEL", provincia: "COLON" },
  { corregimiento: "NOMBRE DE DIOS", distrito: "SANTA ISABEL", provincia: "COLON" },
  { corregimiento: "NUEVA", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "NUEVO CHAGRES", distrito: "CHAGRES", provincia: "COLON" },
  { corregimiento: "PALENQUE", distrito: "SANTA ISABEL", provincia: "COLON" },
  { corregimiento: "PALMAS BELLAS", distrito: "CHAGRES", provincia: "COLON" },
  { corregimiento: "PALMIRA", distrito: "SANTA ISABEL", provincia: "COLON" },
  { corregimiento: "PINA", distrito: "CHAGRES", provincia: "COLON" },
  { corregimiento: "PLAYA CHIQUITA", distrito: "SANTA ISABEL", provincia: "COLON" },
  { corregimiento: "PORTOBELO", distrito: "PORTOBELO", provincia: "COLON" },
  { corregimiento: "PROVIDENCIA", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "PUERTO PILON", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "RIO INDIO", distrito: "DONOSO", provincia: "COLON" },
  { corregimiento: "SABANITAS", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "SALAMANCA", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "SALUD", distrito: "CHAGRES", provincia: "COLON" },
  { corregimiento: "SAN JOSE DEL GENERAL", distrito: "DONOSO", provincia: "COLON" },
  { corregimiento: "SAN JUAN", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "SANTA ISABEL", distrito: "SANTA ISABEL", provincia: "COLON" },
  { corregimiento: "SANTA ROSA", distrito: "COLON", provincia: "COLON" },
  { corregimiento: "VIENTO FRIO", distrito: "SANTA ISABEL", provincia: "COLON" },
  { corregimiento: "CIRILO GUAINORA", distrito: "CEMACO", provincia: "COMARCA EMBERA" },
  { corregimiento: "JINGURUDO", distrito: "SAMBU", provincia: "COMARCA EMBERA" },
  { corregimiento: "LAJAS BLANCAS", distrito: "CEMACO", provincia: "COMARCA EMBERA" },
  { corregimiento: "MANUEL ORTEGA", distrito: "CEMACO", provincia: "COMARCA EMBERA" },
  { corregimiento: "PUERTO INDIO", distrito: "SAMBU", provincia: "COMARCA EMBERA" },
  { corregimiento: "RIO SABALO", distrito: "SAMBU", provincia: "COMARCA EMBERA" },
  { corregimiento: "UNION CHOCOE", distrito: "CEMACO", provincia: "COMARCA EMBERA" },
  { corregimiento: "AKUA YALA", distrito: "COMARCA KUNA DE MADUNGAND", provincia: "COMARCA KUNA DE MADUNGAND" },
  { corregimiento: "MORTI", distrito: "COMARCA KUNA DE WARGANDI", provincia: "COMARCA KUNA DE WARGANDI" },
  { corregimiento: "AILIGANDI", distrito: "NARGANA", provincia: "COMARCA KUNA YALA" },
  { corregimiento: "EL PORVENIR", distrito: "NARGANA", provincia: "COMARCA KUNA YALA" },
  { corregimiento: "PUERTO OBALDIA", distrito: "NARGANA", provincia: "COMARCA KUNA YALA" },
  { corregimiento: "TUBUALA", distrito: "NARGANA", provincia: "COMARCA KUNA YALA" },
  { corregimiento: "AGUA DE SALUD", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "ALTO CABALLERO", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "ALTO DE JESUS", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "BAGAMA", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "BAHIA AZUL", distrito: "KUSAPIN", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "BISIRA", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "BOCA DE SALSA", distrito: "BESIKO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "BUENOS AIRES", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "BURI", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CALOVEBORA O SANTA CATALI", distrito: "KUSAPIN", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CAMARON ARRIBA", distrito: "BESIKO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CASCABEL", distrito: "MIRONO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CERRO BANCO", distrito: "BESIKO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CERRO CANA", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CERRO IGLESIAS", distrito: "NOLE DUIMA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CERRO PATENA", distrito: "BESIKO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CERRO PELADO", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CERRO PUERCO", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "CHICHICA", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "EL BALE", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "EL PAREDON", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "EL PIRO", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "EMPLANADA DE CHORCHA", distrito: "BESIKO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "GUARIVIARA", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "GUAYABITO", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "GUIBALE", distrito: "NURUM", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "GUORONI", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "HATO CHAMI", distrito: "NOLE DUIMA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "HATO COROTU", distrito: "MIRONO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "HATO CULANTRO", distrito: "MIRONO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "HATO JOBO", distrito: "MIRONO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "HATO JULI", distrito: "MIRONO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "HATO PILON", distrito: "MIRONO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "JADEBERI", distrito: "NOLE DUIMA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "KANKINTU", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "KRUA", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "KUSAPIN", distrito: "KUSAPIN", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "LAJERO", distrito: "NOLE DUIMA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "LLANO TUGRI", distrito: "NOLE DUIMA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "LOMA YUCA", distrito: "KUSAPIN", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "MAN CREEK", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "MARACA", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "MUNUNI", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "NAMNONI", distrito: "BESIKO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "NIBA", distrito: "BESIKO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "NIBRA", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "PENA BLANCA", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "PIEDRA ROJA", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "QUEBRADA DE LORO", distrito: "MIRONO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "RIO CHIRIQUI", distrito: "KUSAPIN", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "ROKA", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "SALTO DUPI", distrito: "MIRONO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "SITIO PRADO", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "SOLOY", distrito: "BESIKO", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "SUSAMA", distrito: "NOLE DUIMA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "TOBOBE", distrito: "KUSAPIN", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "TUWAI", distrito: "KANKINTU", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "UMANI", distrito: "MUNA", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "VALLE BONITO", distrito: "KUSAPIN", provincia: "COMARCA NGOBE BUGLE" },
  { corregimiento: "AGUA FRIA", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "BOCA DE CUPE", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "CAMOGANTI", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "CHEPIGANA", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "COMARCA KUNA", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "CUCUNATI", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "EL REAL DE SANTA MARIA", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "GARACHINE", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "JAQUE", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "LA PALMA", distrito: "", provincia: "DARIEN" },
  { corregimiento: "LA PALMA DARIEN", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "METETI", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "PAYA", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "PINOGANA", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "PUCURO", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "PUERTO PINA", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "RIO CONGO", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "RIO CONGO ARRIBA", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "RIO IGLESIAS", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "SAMBU", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "SANTA FE", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "SETEGANTI", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "TAIMATI", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "TUCUTI", distrito: "CHEPIGANA", provincia: "DARIEN" },
  { corregimiento: "WARGANDI", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "YAPE", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "YAVIZA", distrito: "PINOGANA", provincia: "DARIEN" },
  { corregimiento: "CABUYA", distrito: "PARITA", provincia: "HERRERA" },
  { corregimiento: "CAPURI", distrito: "LOS POZOS", provincia: "HERRERA" },
  { corregimiento: "CERRO LARGO", distrito: "OCU", provincia: "HERRERA" },
  { corregimiento: "CHEPO", distrito: "LAS MINAS", provincia: "HERRERA" },
  { corregimiento: "CHITRE", distrito: "CHITRE", provincia: "HERRERA" },
  { corregimiento: "CHUMICAL", distrito: "LAS MINAS", provincia: "HERRERA" },
  { corregimiento: "CHUPAMPA", distrito: "SANTA MARIA", provincia: "HERRERA" },
  { corregimiento: "CORONADO", distrito: "", provincia: "HERRERA" },
  { corregimiento: "EL BARRERO", distrito: "PESE", provincia: "HERRERA" },
  { corregimiento: "EL CALABACITO", distrito: "LOS POZOS", provincia: "HERRERA" },
  { corregimiento: "EL CEDRO", distrito: "LOS POZOS", provincia: "HERRERA" },
  { corregimiento: "EL CIRUELO", distrito: "PESE", provincia: "HERRERA" },
  { corregimiento: "EL LIMON", distrito: "SANTA MARIA", provincia: "HERRERA" },
  { corregimiento: "EL PAJARO", distrito: "PESE", provincia: "HERRERA" },
  { corregimiento: "EL PEDREGOSO", distrito: "PESE", provincia: "HERRERA" },
  { corregimiento: "EL RINCON", distrito: "SANTA MARIA", provincia: "HERRERA" },
  { corregimiento: "EL TIJERA", distrito: "OCU", provincia: "HERRERA" },
  { corregimiento: "EL TORO", distrito: "LAS MINAS", provincia: "HERRERA" },
  { corregimiento: "LA ARENA", distrito: "CHITRE", provincia: "HERRERA" },
  { corregimiento: "LA PITALOZA", distrito: "LOS POZOS", provincia: "HERRERA" },
  { corregimiento: "LA VILLA DE LOS SANTOS", distrito: "", provincia: "HERRERA" },
  { corregimiento: "LAS CABRAS", distrito: "PESE", provincia: "HERRERA" },
  { corregimiento: "LAS LLANAS", distrito: "LOS POZOS", provincia: "HERRERA" },
  { corregimiento: "LAS MINAS", distrito: "LAS MINAS", provincia: "HERRERA" },
  { corregimiento: "LEONES", distrito: "LAS MINAS", provincia: "HERRERA" },
  { corregimiento: "LLANO BONITO", distrito: "CHITRE", provincia: "HERRERA" },
  { corregimiento: "LLANO DE LA CRUZ", distrito: "PARITA", provincia: "HERRERA" },
  { corregimiento: "LLANO GRANDE", distrito: "OCU", provincia: "HERRERA" },
  { corregimiento: "LOS CANELOS", distrito: "SANTA MARIA", provincia: "HERRERA" },
  { corregimiento: "LOS CASTILLOS", distrito: "PARITA", provincia: "HERRERA" },
  { corregimiento: "LOS CERRITOS", distrito: "LOS POZOS", provincia: "HERRERA" },
  { corregimiento: "LOS CERROS DE PAJA", distrito: "LOS POZOS", provincia: "HERRERA" },
  { corregimiento: "LOS LLANOS", distrito: "OCU", provincia: "HERRERA" },
  { corregimiento: "LOS POZOS", distrito: "LOS POZOS", provincia: "HERRERA" },
  { corregimiento: "MENCHACA", distrito: "OCU", provincia: "HERRERA" },
  { corregimiento: "MONAGRILLO", distrito: "CHITRE", provincia: "HERRERA" },
  { corregimiento: "OCU", distrito: "OCU", provincia: "HERRERA" },
  { corregimiento: "PARIS", distrito: "PARITA", provincia: "HERRERA" },
  { corregimiento: "PARITA", distrito: "PARITA", provincia: "HERRERA" },
  { corregimiento: "PENAS CHATAS", distrito: "OCU", provincia: "HERRERA" },
  { corregimiento: "PESE", distrito: "PESE", provincia: "HERRERA" },
  { corregimiento: "PORTOBELILLO", distrito: "PARITA", provincia: "HERRERA" },
  { corregimiento: "POTUGA", distrito: "PARITA", provincia: "HERRERA" },
  { corregimiento: "QUEBRADA DEL ROSARIO", distrito: "LAS MINAS", provincia: "HERRERA" },
  { corregimiento: "QUEBRADA EL CIPRIAN", distrito: "LAS MINAS", provincia: "HERRERA" },
  { corregimiento: "RINCON HONDO", distrito: "PESE", provincia: "HERRERA" },
  { corregimiento: "SABANA GRANDE", distrito: "PESE", provincia: "HERRERA" },
  { corregimiento: "SAN JUAN BAUTISTA", distrito: "CHITRE", provincia: "HERRERA" },
  { corregimiento: "SANTA MARIA", distrito: "SANTA MARIA", provincia: "HERRERA" },
  { corregimiento: "AGUA BUENA", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "ALTOS DE GUERRA", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "BAHIA HONDA", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "BAJO CORRAL", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "BAJOS DE GUERA", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "BAYANO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "CAMBUTAL", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "CANAS GORDAS", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "CHUPA", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "COROZAL", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "EL BEBEDERO", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "EL CACAO", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "EL CANAFISTULO", distrito: "POCRI", provincia: "LOS SANTOS" },
  { corregimiento: "EL CARATE", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "EL CEDRO", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "EL COCAL", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "EL CORTEZO", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "EL ESPIRAL", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "EL GUASIMO", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "EL HATO", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "EL MACANO", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "EL MANANTIAL", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "EL MUNOZ", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "EL PEDRAGOSO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "ESPINO AMARILLO", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "FLORES", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "GUANICO", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "GUARARE", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "GUARARE ARRIBA", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "ISLA DE CANAS", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "LA COLORADA", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "LA ENEA", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "LA ESPIGADILLA", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "LA LAJA", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "LA MESA", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "LA MIEL", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "LA PALMA", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "LA PALMA LOS SANTOS", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "LA PASERA", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "LA TIZA", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "LA TRONOSA", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "LA VILLA DE LOS SANTOS", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "LAJAMINA", distrito: "POCRI", provincia: "LOS SANTOS" },
  { corregimiento: "LAS CRUCES", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "LAS GUABAS", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "LAS PALMAS", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "LAS PALMITAS", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "LAS TABLAS", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "LAS TABLAS ABAJO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "LAS TRANCAS", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "LLANO ABAJO", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "LLANO DE PIEDRA", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "LLANO LARGO", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "LOS ANGELES", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "LOS ASIENTOS", distrito: "PEDASI", provincia: "LOS SANTOS" },
  { corregimiento: "LOS OLIVOS", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "MACARACAS", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "MARIABE", distrito: "PEDASI", provincia: "LOS SANTOS" },
  { corregimiento: "MOGOLLON", distrito: "MACARACAS", provincia: "LOS SANTOS" },
  { corregimiento: "NUARIO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "ORIA ARRIBA", distrito: "PEDASI", provincia: "LOS SANTOS" },
  { corregimiento: "PALMIRA", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "PARAISO", distrito: "POCRI", provincia: "LOS SANTOS" },
  { corregimiento: "PARITILLA", distrito: "POCRI", provincia: "LOS SANTOS" },
  { corregimiento: "PEDASI", distrito: "PEDASI", provincia: "LOS SANTOS" },
  { corregimiento: "PENA BLANCA", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "PERALES", distrito: "GUARARE", provincia: "LOS SANTOS" },
  { corregimiento: "POCRI", distrito: "POCRI", provincia: "LOS SANTOS" },
  { corregimiento: "PURIO", distrito: "PEDASI", provincia: "LOS SANTOS" },
  { corregimiento: "RIO HONDO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "SABANA GRANDE", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "SAN JOSE", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "SAN MIGUEL", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "SANTA ANA", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "SANTO DOMINGO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "SESTEADERO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "TONOSI", distrito: "TONOSI", provincia: "LOS SANTOS" },
  { corregimiento: "TRES QUEBRADAS", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "VALLE RICO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "VALLERRIQUITO", distrito: "LAS TABLAS", provincia: "LOS SANTOS" },
  { corregimiento: "VILLA LOURDES", distrito: "LOS SANTOS", provincia: "LOS SANTOS" },
  { corregimiento: "24 DE DICIEMBRE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "AMADOR", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "AMELIA DENIS DE ICAZA", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "ANCON", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "ARNULFO ARIAS", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "AROSEMENA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "ARRAIJAN", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "BARRIO BALBOA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "BARRIO COLON", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "BEJUCO", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "BELISARIO FRIAS", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "BELISARIO PORRAS", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "BELLA VISTA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "BETHANIA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "BRUJAS", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "BUENOS AIRES", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "BURUNGA", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "CABUYA", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "CAIMITO", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CAMPANA", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CANITA", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "CAPIRA", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CERMENO", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CERRO AZUL", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "CERRO SILVESTRE", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "CHAME", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "CHEPILLO", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "CHEPO", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "CHICA", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "CHILIBRE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "CHIMAN", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "CIRI DE LOS SOTOS", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CIRI GRANDE", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "CIUDAD DE PANAMA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "CIUDAD DE PANAMA OESTE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "CIUDAD PANAMA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "COMARCA KUNA DE MADUGANDI", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "CORONADO", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "CURUNDU", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "EL ARADO", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "EL CACAO", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "EL CHORRILLO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "EL COCO", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "EL ESPINO", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "EL HIGO", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "EL LIBANO", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "EL LLANO", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "ERNESTO CORDOBA CAMPOS", distrito: "", provincia: "PANAMA" },
  { corregimiento: "FEUILLET", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "GONZALO VASQUEZ", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "GUADALUPE", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "GUAYABITO", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "HERRERA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "HERRERA DE CHORRERA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "HURTADO", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "ITURRALDE", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "JOSE DOMINGO ESPINAR", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "JUAN DEMOSTENES AROSEMENA", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "JUAN DIAZ", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "LA CHORRERA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "LA ENSENADA", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "LA ERMITA", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "LA ESMERALDA", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "LA EXPOSICION O CALIDONIA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "LA GUINEA", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "LA LAGUNA", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "LA REPRESA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "LA TRINIDAD", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "LAS CUMBRES", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "LAS LAJAS", distrito: "", provincia: "PANAMA" },
  { corregimiento: "LAS LAJAS CHAME", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "LAS MANANITAS", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "LAS MARGARITAS", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "LAS OLLAS ARRIBA", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "LAS UVAS", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "LIDICE", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "LOS DIAZ", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "LOS LLANITOS", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "MATEO ITURRALDE", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "MENDOZA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "NUEVA GORGONA", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "NUEVO EMPERADOR", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "OBALDIA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "OMAR TORRIJOS", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "OTOQUE OCCIDENTE", distrito: "TABOGA", provincia: "PANAMA" },
  { corregimiento: "OTOQUE ORIENTE", distrito: "TABOGA", provincia: "PANAMA" },
  { corregimiento: "PACORA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "PARQUE LEFEVRE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "PASIGA", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "PEDREGAL", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "PEDRO GONZALEZ", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "PLAYA LEONA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "PUEBLO NUEVO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "PUERTO CAIMITO", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "PUNTA CHAME", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "RIO ABAJO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "RUFINA ALFARO", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "SABOGA", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "SAJALICES", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "SAN CARLOS", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "SAN FELIPE", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SAN FRANCISCO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SAN JOSE", distrito: "SAN CARLOS", provincia: "PANAMA" },
  { corregimiento: "SAN MARTIN", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SAN MIGUEL", distrito: "BALBOA", provincia: "PANAMA" },
  { corregimiento: "SAN MIGUELITO", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SANTA ANA", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "SANTA CLARA", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "SANTA CRUZ DE CHININA", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "SANTA RITA", distrito: "LA CHORRERA", provincia: "PANAMA" },
  { corregimiento: "SANTA ROSA", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "SORA", distrito: "CHAME", provincia: "PANAMA" },
  { corregimiento: "TABOGA", distrito: "TABOGA", provincia: "PANAMA" },
  { corregimiento: "TOCUMEN", distrito: "PANAMA", provincia: "PANAMA" },
  { corregimiento: "TORTI", distrito: "CHEPO", provincia: "PANAMA" },
  { corregimiento: "UNION SANTENA", distrito: "CHIMAN", provincia: "PANAMA" },
  { corregimiento: "VERACRUZ", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "VICTORIANO LORENZO", distrito: "SAN MIGUELITO", provincia: "PANAMA" },
  { corregimiento: "VILLA CARMEN", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "VILLA ROSARIO", distrito: "CAPIRA", provincia: "PANAMA" },
  { corregimiento: "VISTA ALEGRE", distrito: "ARRAIJAN", provincia: "PANAMA" },
  { corregimiento: "ARENAS", distrito: "MARIATO", provincia: "VERAGUAS" },
  { corregimiento: "ATALAYA", distrito: "ATALAYA", provincia: "VERAGUAS" },
  { corregimiento: "BAHIA HONDA", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "BARNIZAL", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "BISVALLES", distrito: "LA MESA", provincia: "VERAGUAS" },
  { corregimiento: "BORO", distrito: "LA MESA", provincia: "VERAGUAS" },
  { corregimiento: "CALIDONIA", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "CALOBRE", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "CALOVEBORA", distrito: "SANTAFE", provincia: "VERAGUAS" },
  { corregimiento: "CANAZAS", distrito: "CANAZAS", provincia: "VERAGUAS" },
  { corregimiento: "CANTO DEL LLANO", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "CARLOS SANTANA AVILA", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "CATIVE", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "CATORCE DE NOVIEMBRE", distrito: "RIO DE JESUS", provincia: "VERAGUAS" },
  { corregimiento: "CEBACO", distrito: "MONTIJO", provincia: "VERAGUAS" },
  { corregimiento: "CERRO DE CASA", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "CERRO DE PLATA", distrito: "CANAZAS", provincia: "VERAGUAS" },
  { corregimiento: "CHITRA", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "COROZAL", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "CORRAL FALSO", distrito: "SAN FRANCISCO", provincia: "VERAGUAS" },
  { corregimiento: "COSTA HERMOSA", distrito: "MONTIJO", provincia: "VERAGUAS" },
  { corregimiento: "EDWIN FABREGA", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "EL ALTO", distrito: "SANTAFE", provincia: "VERAGUAS" },
  { corregimiento: "EL AROMILLO", distrito: "CANAZAS", provincia: "VERAGUAS" },
  { corregimiento: "EL BARRITO", distrito: "ATALAYA", provincia: "VERAGUAS" },
  { corregimiento: "EL CACAO", distrito: "MARIATO", provincia: "VERAGUAS" },
  { corregimiento: "EL COCLA", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "EL CUAY", distrito: "SANTAFE", provincia: "VERAGUAS" },
  { corregimiento: "EL MARANON", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "EL MARIA", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "EL PANTANO", distrito: "SANTAFE", provincia: "VERAGUAS" },
  { corregimiento: "EL PICADOR", distrito: "CANAZAS", provincia: "VERAGUAS" },
  { corregimiento: "EL POTRERO", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "EL PRADO", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "EL RINCON", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "GATUNCITO", distrito: "SANTAFE", provincia: "VERAGUAS" },
  { corregimiento: "GOBERNADORA", distrito: "MONTIJO", provincia: "VERAGUAS" },
  { corregimiento: "GUARUMAL", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "LA CARRILLO", distrito: "ATALAYA", provincia: "VERAGUAS" },
  { corregimiento: "LA COLORADA", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "LA GARCEANA", distrito: "MONTIJO", provincia: "VERAGUAS" },
  { corregimiento: "LA LAGUNA", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "LA MESA", distrito: "LA MESA", provincia: "VERAGUAS" },
  { corregimiento: "LA MONTANUELA", distrito: "ATALAYA", provincia: "VERAGUAS" },
  { corregimiento: "LA PENA", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "LA RAYA DE CALOBRE", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "LA RAYA DE SANTA MARIA", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "LA SOLEDAD", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "LA TETILLA", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "LA YEGUADA", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "LAS CRUCES", distrito: "CANAZAS", provincia: "VERAGUAS" },
  { corregimiento: "LAS GUIAS", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "LAS HUACAS", distrito: "RIO DE JESUS", provincia: "VERAGUAS" },
  { corregimiento: "LAS PALMAS", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "LAS PALMAS VERAGUAS", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "LEONES", distrito: "MONTIJO", provincia: "VERAGUAS" },
  { corregimiento: "LLANO DE CATIVAL O MARIAT", distrito: "MARIATO", provincia: "VERAGUAS" },
  { corregimiento: "LLANO GRANDE", distrito: "LA MESA", provincia: "VERAGUAS" },
  { corregimiento: "LOS ALGARROBOS", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "LOS CASTILLOS", distrito: "RIO DE JESUS", provincia: "VERAGUAS" },
  { corregimiento: "LOS HATILLOS", distrito: "SAN FRANCISCO", provincia: "VERAGUAS" },
  { corregimiento: "LOS MILAGROS", distrito: "LA MESA", provincia: "VERAGUAS" },
  { corregimiento: "LOS VALLES", distrito: "CANAZAS", provincia: "VERAGUAS" },
  { corregimiento: "MONJARAS", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "MONTIJO", distrito: "MONTIJO", provincia: "VERAGUAS" },
  { corregimiento: "OLA", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "PILON", distrito: "MONTIJO", provincia: "VERAGUAS" },
  { corregimiento: "PIXVAE", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "PONUGA", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "PUERTO VIDAL", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "QUEBRADA DE ORO", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "QUEBRO", distrito: "MARIATO", provincia: "VERAGUAS" },
  { corregimiento: "REMANCE", distrito: "SAN FRANCISCO", provincia: "VERAGUAS" },
  { corregimiento: "RIO DE JESUS", distrito: "RIO DE JESUS", provincia: "VERAGUAS" },
  { corregimiento: "RIO GRANDE", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "RIO LUIS", distrito: "SANTAFE", provincia: "VERAGUAS" },
  { corregimiento: "RODEO VIEJO", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "RUBEN CANTU", distrito: "SANTAFE", provincia: "VERAGUAS" },
  { corregimiento: "SAN ANTONIO", distrito: "ATALAYA", provincia: "VERAGUAS" },
  { corregimiento: "SAN BARTOLO", distrito: "LA MESA", provincia: "VERAGUAS" },
  { corregimiento: "SAN FRANCISCO", distrito: "SAN FRANCISCO", provincia: "VERAGUAS" },
  { corregimiento: "SAN JOSE", distrito: "CALOBRE", provincia: "VERAGUAS" },
  { corregimiento: "SAN JUAN", distrito: "SAN FRANCISCO", provincia: "VERAGUAS" },
  { corregimiento: "SAN MARCELO", distrito: "CANAZAS", provincia: "VERAGUAS" },
  { corregimiento: "SAN MARTIN DE PORRES", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "SAN PEDRO DEL ESPINO", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "SANTAFE", distrito: "SANTAFE", provincia: "VERAGUAS" },
  { corregimiento: "SANTIAGO", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "SONA", distrito: "SONA", provincia: "VERAGUAS" },
  { corregimiento: "TEBARIO", distrito: "MARIATO", provincia: "VERAGUAS" },
  { corregimiento: "UNION DEL NORTE", distrito: "MONTIJO", provincia: "VERAGUAS" },
  { corregimiento: "URRACA", distrito: "SANTIAGO", provincia: "VERAGUAS" },
  { corregimiento: "UTIRA", distrito: "RIO DE JESUS", provincia: "VERAGUAS" },
  { corregimiento: "VIGUI", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
  { corregimiento: "ZAPOTILLO", distrito: "LAS PALMAS", provincia: "VERAGUAS" },
];
